/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package LoanEnterprise;

import VisaEnterprise.StudentVisaDetailsJFrame;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class LoanFinalJPanel extends javax.swing.JPanel {
private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
     String name,pass;
     byte[] image;
     DefaultTableModel recordTable;
    /**
     * Creates new form LoanFinalJPanel
     */
    public LoanFinalJPanel() {
        initComponents();
    }
public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from loandetaislfinal");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         
         DefaultTableModel recordTable=(DefaultTableModel) apptbl.getModel();
         recordTable.setRowCount(0);
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  columnData.add(rs.getString("ID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("LoanPartner"));
                  columnData.add(rs.getString("Income"));
                  columnData.add(rs.getString("Score"));
                  columnData.add(rs.getString("InterestRate"));
                  
                  columnData.add(rs.getString("Status"));
                }         
            recordTable.addRow(columnData);
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        apptbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        apptbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Loan Partner", "Annual Income", "Score", "Interest Rate", "Status"
            }
        ));
        apptbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(apptbl);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataconn,username,password);
            pst=sqlConn.prepareStatement("select * from loandetailsfinal");

            rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)apptbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {

                String id=String.valueOf(rs.getString("ID"));
                String name=String.valueOf(rs.getString("Name"));
                String lp=String.valueOf(rs.getString("LoanPartner"));
                String ai=String.valueOf(rs.getString("Income"));
                String score=String.valueOf(rs.getString("Score"));
                String ir=String.valueOf(rs.getString("InterestRate"));
                String status=String.valueOf(rs.getString("Status"));
                
               

                String tbdata[]={id,name,lp,ai,score,ir,status};

                model.addRow(tbdata);
            }

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void apptblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptblMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)apptbl.getModel();
         int SelectedRows= apptbl.getSelectedRow();
         String status=model.getValueAt(SelectedRows, 6).toString();
         String nstatus=JOptionPane.showInputDialog(null, "Loan Status",status);
         model.setValueAt(nstatus, SelectedRows, 6);
               try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("update loandetailsfinal set ID=?,Name=?,LoanPartner=?,Income=?,Score=?, InterestRate=?,Status=? where ID=?");
         
       pst.setString(1,model.getValueAt(SelectedRows, 0).toString());
        pst.setString(2,model.getValueAt(SelectedRows, 1).toString());
        pst.setString(3,model.getValueAt(SelectedRows, 2).toString());
        pst.setString(4,model.getValueAt(SelectedRows, 3).toString());
        pst.setString(5,model.getValueAt(SelectedRows, 4).toString());
        pst.setString(6,model.getValueAt(SelectedRows, 5).toString());
        pst.setString(7,model.getValueAt(SelectedRows, 6).toString());
        pst.setString(8,model.getValueAt(SelectedRows, 0).toString());
        
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Status Updated Successfully");
         upDateDb();}                    
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
    }//GEN-LAST:event_apptblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable apptbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
