/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CounsellingEnterprise;
import javax.swing.event.MouseInputListener;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.VirtualEarthTileFactoryInfo;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.viewer.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Deepak
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
    public ContactUs() {
        initComponents(); 
        init();
    }
    
    
    public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from contact");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  columnData.add(rs.getString("UserID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                  columnData.add(rs.getString("Subject"));
                  columnData.add(rs.getString("Enterprise"));
                  columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Message"));
                  columnData.add(rs.getString("status"));
                }         
            
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    
    } 
private void init(){
       TileFactoryInfo info = new OSMTileFactoryInfo();
        DefaultTileFactory tileFactory = new DefaultTileFactory(info);
        jXMapViewer.setTileFactory(tileFactory);
        GeoPosition geo = new GeoPosition(20.5937,78.9629); 
        jXMapViewer.setAddressLocation(geo);
        jXMapViewer.setZoom(12);

        //  Create event mouse move
        MouseInputListener mm = new PanMouseInputListener(jXMapViewer);
        jXMapViewer.addMouseListener(mm);
        jXMapViewer.addMouseMotionListener(mm);
        jXMapViewer.addMouseWheelListener(new ZoomMouseWheelListenerCenter(jXMapViewer));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jXMapViewer = new org.jxmapviewer.JXMapViewer();
        mapcbox = new javax.swing.JComboBox<>();
        emaillbl = new javax.swing.JLabel();
        mobiletxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        mobilelbl = new javax.swing.JLabel();
        enterpriselbl = new javax.swing.JLabel();
        branchlbl = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        subjecttxt = new javax.swing.JTextField();
        branchcbox = new javax.swing.JComboBox<>();
        messagelbl = new javax.swing.JLabel();
        messagetxt = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        subjectlbl = new javax.swing.JLabel();
        enterprisecbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mapcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open Street", "Virtual Earth", "Hybrid", "Satellite" }));
        mapcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapcboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXMapViewerLayout = new javax.swing.GroupLayout(jXMapViewer);
        jXMapViewer.setLayout(jXMapViewerLayout);
        jXMapViewerLayout.setHorizontalGroup(
            jXMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(mapcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jXMapViewerLayout.setVerticalGroup(
            jXMapViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(mapcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jPanel1.add(jXMapViewer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        emaillbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        emaillbl.setText("Email");
        jPanel1.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 84, -1));

        mobiletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletxtActionPerformed(evt);
            }
        });
        jPanel1.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 235, -1));

        namelbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        namelbl.setText("Name");
        jPanel1.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 84, -1));

        nametxt.setToolTipText("");
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 235, -1));

        mobilelbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        mobilelbl.setText("Mobile No.");
        jPanel1.add(mobilelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 84, -1));

        enterpriselbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        enterpriselbl.setText("Enterprise");
        jPanel1.add(enterpriselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 84, -1));

        branchlbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        branchlbl.setText("Branch");
        jPanel1.add(branchlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 84, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 235, -1));

        subjecttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjecttxtActionPerformed(evt);
            }
        });
        jPanel1.add(subjecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 236, -1));

        branchcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Mumbai", "Bangalore" }));
        jPanel1.add(branchcbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 236, -1));

        messagelbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        messagelbl.setText("Message");
        jPanel1.add(messagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 84, -1));

        messagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagetxtActionPerformed(evt);
            }
        });
        jPanel1.add(messagetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 236, 112));

        submitbtn.setBackground(new java.awt.Color(255, 51, 51));
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 750, 85, -1));

        subjectlbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        subjectlbl.setText("Subject");
        jPanel1.add(subjectlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 84, -1));

        enterprisecbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Career Counselling", "Test Preparation", "Getting Visa ", "Related to Loans", " " }));
        jPanel1.add(enterprisecbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 230, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DROP US A LINE");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 211, 40));

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapcboxActionPerformed
        // TODO add your handling code here:
        TileFactoryInfo info;
        int index = mapcbox.getSelectedIndex();
        if (index == 0) {
            info = new OSMTileFactoryInfo();
        } else if (index == 1) {
            info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.MAP);
        } else if (index == 2) {
            info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.HYBRID);
        } else {
            info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.SATELLITE);
        }
        DefaultTileFactory tileFactory = new DefaultTileFactory(info);
        jXMapViewer.setTileFactory(tileFactory);
    }//GEN-LAST:event_mapcboxActionPerformed

    private void mobiletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void subjecttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjecttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjecttxtActionPerformed

    private void messagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messagetxtActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("INSERT INTO contact(Name,Email,Mobile,Subject,Enterprise,Branch,Message,Status)values(?,?,?,?,?,?,?,?)");
         
          pst.setString(1,nametxt.getText());
          pst.setString(2,emailtxt.getText());
          pst.setString(3,mobiletxt.getText());
          pst.setString(4,subjecttxt.getText());
          enterprise=enterprisecbox.getSelectedItem().toString();
          pst.setString(5,enterprise);
          branch=branchcbox.getSelectedItem().toString();
          pst.setString(6,branch);
          pst.setString(7,messagetxt.getText());
          String status="Requested a Call";
          pst.setString(8,status);
          pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Message Send Successfully");
        upDateDb();
        
    }//GEN-LAST:event_submitbtnActionPerformed
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
        }
    
    
    
    }
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        MainFrame m=new MainFrame();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

        
        
        
       
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchcbox;
    private javax.swing.JLabel branchlbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JComboBox<String> enterprisecbox;
    private javax.swing.JLabel enterpriselbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jxmapviewer.JXMapViewer jXMapViewer;
    private javax.swing.JComboBox<String> mapcbox;
    private javax.swing.JLabel messagelbl;
    private javax.swing.JTextField messagetxt;
    private javax.swing.JLabel mobilelbl;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel subjectlbl;
    private javax.swing.JTextField subjecttxt;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
