/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CounsellingEnterprise;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Deepak
 */
public class EmployeeCCredentialsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeCredentialsJPanel
     */
    
    private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int i,q;
    String employeetype,n;
            int deleteItem;
    public EmployeeCCredentialsJPanel() {
        initComponents();
        scaleImage1();
    }
    public void scaleImage1(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Deepak Sawalka\\Documents\\Final_AED_Project\\FinalProject\\src\\icon\\logo.jpg");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(iconlbl.getWidth(), iconlbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        iconlbl.setIcon(scaledIcon);}
    
        
public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from employeecounsellingcredentials");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         DefaultTableModel recordTable=(DefaultTableModel) credentialstbl.getModel();
         recordTable.setRowCount(0);
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  
                  columnData.add(rs.getString("EmployeeType"));
                  columnData.add(rs.getString("Username"));
                  columnData.add(rs.getString("Password"));
                }         
            
             recordTable.addRow(columnData);
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        credentialstbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        typecbox = new javax.swing.JComboBox<>();
        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        createbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        modifybtn = new javax.swing.JButton();
        iconlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        credentialstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EmployeeType", "Username", "Password"
            }
        ));
        credentialstbl.setGridColor(new java.awt.Color(255, 153, 51));
        credentialstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                credentialstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(credentialstbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(194, 40, 500, 110);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Employee Type");
        add(jLabel1);
        jLabel1.setBounds(270, 270, 107, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(270, 330, 66, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(270, 390, 66, 16);

        typecbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Counsellor", "Admission", " " }));
        add(typecbox);
        typecbox.setBounds(420, 270, 157, 22);
        add(usernametxt);
        usernametxt.setBounds(420, 330, 157, 22);

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        add(passwordtxt);
        passwordtxt.setBounds(420, 390, 157, 22);

        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });
        add(createbtn);
        createbtn.setBounds(410, 470, 72, 23);

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        add(viewbtn);
        viewbtn.setBounds(200, 180, 72, 23);

        modifybtn.setText("Modify");
        modifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybtnActionPerformed(evt);
            }
        });
        add(modifybtn);
        modifybtn.setBounds(620, 180, 72, 23);
        add(iconlbl);
        iconlbl.setBounds(10, 10, 130, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("INSERT INTO employeecounsellingcredentials(EmployeeType,Username,Password)values(?,?,?)");
         
         
         employeetype=typecbox.getSelectedItem().toString();
          pst.setString(1,employeetype);
          pst.setString(2,usernametxt.getText());
           pst.setString(3,passwordtxt.getText());
          
          pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Credentials Added Successfully");
        upDateDb();
        typecbox.setSelectedItem("--Select--");
    usernametxt.setText("");
    passwordtxt.setText("");
    }
           
           catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
        }
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from employeecounsellingcredentials");
            
             rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)credentialstbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                
                
                
                String employeetype=String.valueOf(rs.getString("EmployeeType"));
                String username=String.valueOf(rs.getString("Username"));
                String password=String.valueOf(rs.getString("Password"));
                
                String tbdata[]={employeetype,username,password};
                
                model.addRow(tbdata);
            }
           
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_createbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from employeecounsellingcredentials");
            
             rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)credentialstbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                
                
                
                String employeetype=String.valueOf(rs.getString("EmployeeType"));
                String username=String.valueOf(rs.getString("Username"));
                String password=String.valueOf(rs.getString("Password"));
                
                String tbdata[]={employeetype,username,password};
                
                model.addRow(tbdata);
            }
           
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void modifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybtnActionPerformed
        // TODO add your handling code here:
         try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("update employeecounsellingcredentials set EmployeeType=?,Username=?,Password=? where Password=?");
         
         employeetype=typecbox.getSelectedItem().toString();
          pst.setString(1,employeetype);
         pst.setString(2,usernametxt.getText());
        pst.setString(3,passwordtxt.getText());
        pst.setString(4,passwordtxt.getText());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Credentials Updated Successfully");
         upDateDb();
         typecbox.setSelectedItem("--Select--");
        usernametxt.setText("");
        passwordtxt.setText("");
         
    }                                         
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from employeecounsellingcredentials");
            
             rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)credentialstbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                
                
                String employeetype=String.valueOf(rs.getString("EmployeeType"));
                String username=String.valueOf(rs.getString("Username"));
                String password=String.valueOf(rs.getString("Password"));
                
                String tbdata[]={employeetype,username,password};
                
                model.addRow(tbdata);
            }
           
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
          
    }//GEN-LAST:event_modifybtnActionPerformed

    private void credentialstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_credentialstblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) credentialstbl.getModel();
        int SelectedRows= credentialstbl.getSelectedRow();
        
        typecbox.setSelectedItem(recordTable.getValueAt(SelectedRows, 0).toString());
        usernametxt.setText(recordTable.getValueAt(SelectedRows, 1).toString());
        passwordtxt.setText(recordTable.getValueAt(SelectedRows, 2).toString());
    }//GEN-LAST:event_credentialstblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createbtn;
    private javax.swing.JTable credentialstbl;
    private javax.swing.JLabel iconlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton modifybtn;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JComboBox<String> typecbox;
    private javax.swing.JTextField usernametxt;
    public javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
