/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CounsellingEnterprise;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Deepak
 */
public class FirstTimeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstTimeJPanel
     */
    private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
    public FirstTimeJPanel() {
        initComponents();
    }
public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from firsttime");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         
         DefaultTableModel recordTable=(DefaultTableModel) firsttimetbl.getModel();
         recordTable.setRowCount(0);
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  columnData.add(rs.getString("UserID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                  columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Enterprise"));
                  columnData.add(rs.getString("Date"));
                  columnData.add(rs.getString("Timeslot"));
                  columnData.add(rs.getString("status"));
                }         
            recordTable.addRow(columnData);
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    }
public void upDateDb1()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from firsttimeupdate");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         
         
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  columnData.add(rs.getString("UserID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                  columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Enterprise"));
                  columnData.add(rs.getString("Date"));
                  columnData.add(rs.getString("Timeslot"));
                  columnData.add(rs.getString("status"));
                }         
          
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        firsttimetbl = new javax.swing.JTable();
        viewbtn = new javax.swing.JButton();
        assignedbtn = new javax.swing.JButton();

        firsttimetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "Name", "Email", "Mobile", "Branch", "Enterprise", "Date", "Time Slot", "Status"
            }
        ));
        firsttimetbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firsttimetblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(firsttimetbl);

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        assignedbtn.setText("Assigned");
        assignedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignedbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(viewbtn)
                .addGap(100, 100, 100)
                .addComponent(assignedbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewbtn)
                    .addComponent(assignedbtn))
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from firsttime");
         
             rs=pst.executeQuery();
            
            DefaultTableModel model=(DefaultTableModel)firsttimetbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                String userid=String.valueOf(rs.getString("UserID"));
                String name=String.valueOf(rs.getString("Name"));
                String email=String.valueOf(rs.getString("Email"));
                String mobile=String.valueOf(rs.getString("Mobile"));
                String branch=String.valueOf(rs.getString("Branch"));
                String enterprise=String.valueOf(rs.getString("Enterprise"));
                String date=String.valueOf(rs.getString("Date"));
                String timeslot=String.valueOf(rs.getString("Timeslot"));
                String s=String.valueOf(rs.getString("status"));
                
                String tbdata[]={userid,name,email,mobile,branch,enterprise,date,timeslot,s};
                
                model.addRow(tbdata);
            }
           
        }
      
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void firsttimetblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firsttimetblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)firsttimetbl.getModel();
         int SelectedRows= firsttimetbl.getSelectedRow();
         String nstatus="Alloted";
         
         model.setValueAt(nstatus, SelectedRows, 8);
               try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("update firsttime set UserID=?,Name=?,Email=?,Mobile=?,Branch=?, Enterprise=?,Date=?,Timeslot=?,status=? where UserID=?");
         
       pst.setString(1,model.getValueAt(SelectedRows, 0).toString());
        pst.setString(2,model.getValueAt(SelectedRows, 1).toString());
        pst.setString(3,model.getValueAt(SelectedRows, 2).toString());
        pst.setString(4,model.getValueAt(SelectedRows, 3).toString());
        pst.setString(5,model.getValueAt(SelectedRows, 4).toString());
        pst.setString(6,model.getValueAt(SelectedRows, 5).toString());
        pst.setString(7,model.getValueAt(SelectedRows, 6).toString());
        pst.setString(8,model.getValueAt(SelectedRows, 7).toString());
        pst.setString(9,model.getValueAt(SelectedRows, 8).toString());
        pst.setString(10,model.getValueAt(SelectedRows, 0).toString());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Status Updated Successfully");
         upDateDb();}                    
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
     
    }//GEN-LAST:event_firsttimetblMouseClicked

    private void assignedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignedbtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)firsttimetbl.getModel();
         int SelectedRows= firsttimetbl.getSelectedRow();
         String nstatus="Alloted";
         //String nstatus=JOptionPane.showInputDialog(null, "Update Status",status);
         model.setValueAt(nstatus, SelectedRows, 8);
               try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
        
         pst=sqlConn.prepareStatement("INSERT INTO firsttimeupdate(UserID,Name,Email,Mobile,Branch,Enterprise,Date,Timeslot,status)values(?,?,?,?,?,?,?,?,?)");
       pst.setString(1,model.getValueAt(SelectedRows, 0).toString());
        pst.setString(2,model.getValueAt(SelectedRows, 1).toString());
        pst.setString(3,model.getValueAt(SelectedRows, 2).toString());
        pst.setString(4,model.getValueAt(SelectedRows, 3).toString());
        pst.setString(5,model.getValueAt(SelectedRows, 4).toString());
        pst.setString(6,model.getValueAt(SelectedRows, 5).toString());
        pst.setString(7,model.getValueAt(SelectedRows, 6).toString());
        pst.setString(8,model.getValueAt(SelectedRows, 7).toString());
        pst.setString(9,model.getValueAt(SelectedRows, 8).toString());
        
         pst.executeUpdate();
         
         upDateDb1();}                    
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
               JOptionPane.showMessageDialog(this,"Assigned to Counsellor");
    }//GEN-LAST:event_assignedbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignedbtn;
    private javax.swing.JTable firsttimetbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
