/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CounsellingEnterprise;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Deepak
 */
public class Forex extends javax.swing.JPanel {

    /**
     * Creates new form Forex
     */
    public Forex() {
        initComponents();
         scaleImage1();
          scaleImage2();
          scaleImage3();
    }
     public void scaleImage1(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Deepak Sawalka\\Documents\\FinalAEDProject_Github\\Final_AED_Project\\FinalProject\\src\\icon\\logo.jpg");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(iconlbl.getWidth(), iconlbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        iconlbl.setIcon(scaledIcon);}
      public void scaleImage2(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Deepak Sawalka\\Documents\\FinalAEDProject_Github\\Final_AED_Project\\FinalProject\\src\\icon\\tc.png");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(thomaslbl.getWidth(), thomaslbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        thomaslbl.setIcon(scaledIcon);}
      public void scaleImage3(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Deepak Sawalka\\Documents\\FinalAEDProject_Github\\Final_AED_Project\\FinalProject\\src\\icon\\ab.jpg");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(axislbl.getWidth(), axislbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        axislbl.setIcon(scaledIcon);}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        axislbl = new javax.swing.JLabel();
        thomaslbl = new javax.swing.JLabel();
        iconlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Our Forex Partners:");
        add(jLabel6);
        jLabel6.setBounds(320, 20, 247, 33);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("1. Thomas Cook Forex Card:");
        add(jLabel7);
        jLabel7.setBounds(10, 130, 196, 19);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("Thomas Cook offers the following Benefits :");
        add(jLabel12);
        jLabel12.setBounds(20, 160, 306, 19);

        jLabel10.setText("1.Complete Online services for remittance of Tuition Fees");
        add(jLabel10);
        jLabel10.setBounds(30, 190, 301, 16);

        jLabel9.setText("2.Very low mark up for Forex Prepaid Card and Currency Notes");
        add(jLabel9);
        jLabel9.setBounds(30, 220, 330, 16);

        jButton1.setText("More Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 430, 100, 23);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setText("2. Axis Bank Multicurrency Card:");
        add(jLabel11);
        jLabel11.setBounds(10, 300, 226, 19);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Axis Bank offers the following Benefits :");
        add(jLabel8);
        jLabel8.setBounds(20, 330, 280, 19);

        jLabel13.setText("1.Protection from fluctuations in exchange rate");
        add(jLabel13);
        jLabel13.setBounds(30, 370, 249, 16);

        jLabel14.setText("2.Worldwide Acceptance");
        add(jLabel14);
        jLabel14.setBounds(30, 400, 131, 16);

        jButton2.setText("More Info");
        add(jButton2);
        jButton2.setBounds(20, 250, 100, 23);
        add(axislbl);
        axislbl.setBounds(480, 310, 150, 140);
        add(thomaslbl);
        thomaslbl.setBounds(480, 120, 150, 140);
        add(iconlbl);
        iconlbl.setBounds(30, 10, 120, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel axislbl;
    private javax.swing.JLabel iconlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel thomaslbl;
    // End of variables declaration//GEN-END:variables
}
