/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CounsellingEnterprise;

import Ecosystem.EnterpriseAdminLogin;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class StudentAcc extends javax.swing.JFrame {

    /**
     * Creates new form StudentAcc
     */
     byte[] image=null;
     String gender,hear,fin;
     DefaultTableModel recordTable;
     File f=null;
     String path=null;
     private ImageIcon format=null;
     int s=0;
    public StudentAcc() {
        initComponents();
        scaleImage();
    }
     public void scaleImage(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Deepak Sawalka\\Documents\\FinalAEDProject_Github\\Final_AED_Project\\FinalProject\\src\\icon\\vector.jpg");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(welcomelbl.getWidth(), welcomelbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        welcomelbl.setIcon(scaledIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        profilebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        namelbl = new javax.swing.JLabel();
        imglbl = new javax.swing.JLabel();
        docbtn = new javax.swing.JButton();
        unibtn = new javax.swing.JButton();
        visabtn = new javax.swing.JButton();
        loanbtn = new javax.swing.JButton();
        contactbtn = new javax.swing.JButton();
        feedbackbtn = new javax.swing.JButton();
        forexbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        welcomelbl = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(0, 255, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Rs. 40000");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Fees");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        profilebtn.setBackground(new java.awt.Color(255, 153, 0));
        profilebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilebtn.setForeground(new java.awt.Color(255, 255, 255));
        profilebtn.setText("Profile");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });

        backbtn.setText("<<");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        namelbl.setForeground(new java.awt.Color(255, 255, 255));

        docbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        docbtn.setForeground(new java.awt.Color(255, 255, 255));
        docbtn.setText("Document Management");
        docbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docbtnActionPerformed(evt);
            }
        });

        unibtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unibtn.setForeground(new java.awt.Color(255, 255, 255));
        unibtn.setText("University Shortlisting");
        unibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unibtnActionPerformed(evt);
            }
        });

        visabtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        visabtn.setForeground(new java.awt.Color(255, 255, 255));
        visabtn.setText("VISA");
        visabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visabtnActionPerformed(evt);
            }
        });

        loanbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setText("Loan Management");
        loanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanbtnActionPerformed(evt);
            }
        });

        contactbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactbtn.setForeground(new java.awt.Color(255, 255, 255));
        contactbtn.setText("Contact Us");
        contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactbtnActionPerformed(evt);
            }
        });

        feedbackbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        feedbackbtn.setForeground(new java.awt.Color(255, 255, 255));
        feedbackbtn.setText("Counselling Feedback");
        feedbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackbtnActionPerformed(evt);
            }
        });

        forexbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forexbtn.setForeground(new java.awt.Color(255, 255, 255));
        forexbtn.setText("Forex ");
        forexbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forexbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imglbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(docbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unibtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loanbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contactbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(feedbackbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forexbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilebtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backbtn)
                .addGap(28, 28, 28)
                .addComponent(imglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(docbtn)
                .addGap(31, 31, 31)
                .addComponent(unibtn)
                .addGap(36, 36, 36)
                .addComponent(visabtn)
                .addGap(27, 27, 27)
                .addComponent(loanbtn)
                .addGap(32, 32, 32)
                .addComponent(forexbtn)
                .addGap(18, 18, 18)
                .addComponent(contactbtn)
                .addGap(18, 18, 18)
                .addComponent(feedbackbtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(683, 16, 90, 23);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Total Paid");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Rs. 40000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(104, 136, 192, 101);

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Rs. 0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Pending");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(584, 136, 190, 101);

        jPanel6.setBackground(new java.awt.Color(0, 255, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Rs. 40000");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Total Fees");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(15, 15, 15))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(338, 136, 196, 101);
        jPanel3.add(welcomelbl);
        welcomelbl.setBounds(0, 250, 780, 410);

        jSplitPane1.setRightComponent(jPanel3);

        jScrollPane1.setViewportView(jSplitPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        MainFrame m=new MainFrame();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
        String name=namelbl.getText();
        
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject","root","Rajkumar123#");
            String s= "select * from createstudentprofile where Name=?";
            PreparedStatement ps=conn.prepareStatement(s);
            ps.setString(1, name);
            ResultSet rs=ps.executeQuery();
            if(rs.next()==true){
                StudentManageProfileJPanel sm=new  StudentManageProfileJPanel();
               String pname=String.valueOf(rs.getString("Name"));
               String page=String.valueOf(rs.getString("Age"));
               String pgender=String.valueOf(rs.getString("Gender"));
               String pemail=String.valueOf(rs.getString("Email"));
               String pmobile=String.valueOf(rs.getString("Mobile"));
             
               
                sm.nametxt.setText(pname);
                sm.agetxt.setText(page);
                sm.gendercbox.setSelectedItem(pgender);
                sm.emailtxt.setText(pemail);
                sm.mobiletxt.setText(pmobile);
                
                 
               jSplitPane1.setRightComponent(sm);
            }
        
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_profilebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        String name=namelbl.getText();
        
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject","root","Rajkumar123#");
            String s= "select * from updatestudentprofile where Name=?";
            PreparedStatement ps=conn.prepareStatement(s);
            ps.setString(1, name);
            ResultSet rs=ps.executeQuery();
            if(rs.next()==true){
                
                StudentAcc sa=new StudentAcc();
               String pname=String.valueOf(rs.getString("Name"));
               
               byte[] imagedata=rs.getBytes("Image");
               format=new ImageIcon(imagedata);
               Image mm=format.getImage();

Image img =mm.getScaledInstance(imglbl.getWidth(), imglbl.getHeight(), Image.SCALE_SMOOTH);
 ImageIcon imgae=new ImageIcon(img);
    
                sa.namelbl.setText(pname);
                
                sa.imglbl.setIcon(imgae);
                dispose();
                  sa.setVisible(true);
               
            }
        
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
      
    }//GEN-LAST:event_backbtnActionPerformed

    private void docbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docbtnActionPerformed
        // TODO add your handling code here:
        DocumentJPanel d=new DocumentJPanel();
        jSplitPane1.setRightComponent(d);
    }//GEN-LAST:event_docbtnActionPerformed

    private void unibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unibtnActionPerformed
        // TODO add your handling code here:
          String name=namelbl.getText();
        
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject","root","Rajkumar123#");
            String s= "select * from createstudentprofile where Name=?";
            PreparedStatement ps=conn.prepareStatement(s);
            ps.setString(1, name);
            ResultSet rs=ps.executeQuery();
            if(rs.next()==true){
               AdmissionJPanel a=new AdmissionJPanel();
               String pname=String.valueOf(rs.getString("Name"));
               
             
               
                a.namelbl.setText(pname);
               
                
                 
               jSplitPane1.setRightComponent(a);
            }
        
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
       
    }//GEN-LAST:event_unibtnActionPerformed

    private void contactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactbtnActionPerformed
        // TODO add your handling code here:
        ContactUsJPanel cu=new ContactUsJPanel();
        jSplitPane1.setRightComponent(cu);
    }//GEN-LAST:event_contactbtnActionPerformed

    private void feedbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackbtnActionPerformed
        // TODO add your handling code here:
          FeedbackJPanel f=new FeedbackJPanel();
        jSplitPane1.setRightComponent(f);
    }//GEN-LAST:event_feedbackbtnActionPerformed

    private void visabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visabtnActionPerformed
        // TODO add your handling code here:
        VisaJPanel v=new VisaJPanel();
        jSplitPane1.setRightComponent(v);
    }//GEN-LAST:event_visabtnActionPerformed

    private void forexbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forexbtnActionPerformed
        // TODO add your handling code here:
        Forex f=new Forex();
        jSplitPane1.setRightComponent(f);
    }//GEN-LAST:event_forexbtnActionPerformed

    private void loanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanbtnActionPerformed
        // TODO add your handling code here:
        
        String name=namelbl.getText();
        
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject","root","Rajkumar123#");
            String s= "select * from studentclassdetailsloanall where Name=?";
            PreparedStatement ps=conn.prepareStatement(s);
            ps.setString(1, name);
            ResultSet rs=ps.executeQuery();
            if(rs.next()==true){
                LoanJPanel l=new LoanJPanel();
               String pname=String.valueOf(rs.getString("Name"));
                   String status=String.valueOf(rs.getString("Status"));
              String score=String.valueOf(rs.getString("Test"));
               
                l.userlbl.setText(pname);
                l.loanstatuslbl.setText(status);
                l.grescoretxt.setText(score);
               
                
                 
               jSplitPane1.setRightComponent(l);
            }
        
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
        
    }//GEN-LAST:event_loanbtnActionPerformed

   
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    public javax.swing.JButton contactbtn;
    public javax.swing.JButton docbtn;
    public javax.swing.JButton feedbackbtn;
    public javax.swing.JButton forexbtn;
    public javax.swing.JLabel imglbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JButton loanbtn;
    public javax.swing.JLabel namelbl;
    public javax.swing.JButton profilebtn;
    public javax.swing.JButton unibtn;
    public javax.swing.JButton visabtn;
    private javax.swing.JLabel welcomelbl;
    // End of variables declaration//GEN-END:variables
}
