/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VisaEnterprise;

/**
 *
 * @author vatsal
 */
import CoachingEnterprise.StudentClassDetailsJFrame;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ManageStudentProfileV extends javax.swing.JPanel {
private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
     String name,pass;
     byte[] image;
     DefaultTableModel recordTable;
    /**
     * Creates new form ManageStudentProfileV
     */
    public ManageStudentProfileV() {
        initComponents();
        scaleImage1();
    }
     public void scaleImage1(){
        ImageIcon icon=new ImageIcon("C:\\Users\\vatsal\\Documents\\Github\\Final_AED_Project\\Final_AED_Project\\FinalProject\\src\\icon\\logo.jpg");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(iconlbl.getWidth(), iconlbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        iconlbl.setIcon(scaledIcon);}
    public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailscoachingall");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
   
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  
                  columnData.add(rs.getString("ID"));
                  columnData.add(rs.getString("Name"));
                  columnData.add(rs.getString("Age"));
                  columnData.add(rs.getString("Gender"));
                  columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                  columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Enterprise"));
                  columnData.add(rs.getString("Degree"));
                  columnData.add(rs.getString("Countries"));
                  columnData.add(rs.getBytes("Test"));
                  columnData.add(rs.getString("EnglishTest"));
                 
                }         
            
             
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        managetbl = new javax.swing.JTable();
        viewbtn = new javax.swing.JButton();
        iconlbl = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        managetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Email", "Mobile", "Branch", "Enterprise", "Degree", "Countries", "Test Score", "English Proficiency Test"
            }
        ));
        managetbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managetblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(managetbl);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 180, 961, 207);

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewbtn);
        viewbtn.setBounds(450, 420, 72, 23);
        jPanel1.add(iconlbl);
        iconlbl.setBounds(90, 40, 120, 110);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managetblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managetblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel recordTable=(DefaultTableModel)managetbl.getModel();
         int SelectedRows= managetbl.getSelectedRow();
         
         StudentVisaDetailsJFrame sc=new StudentVisaDetailsJFrame();
         
         sc.nametxt.setText(recordTable.getValueAt(SelectedRows, 1).toString());
sc.agetxt.setText(recordTable.getValueAt(SelectedRows, 2).toString());
sc.gendertxt.setText(recordTable.getValueAt(SelectedRows, 3).toString());
sc.emailtxt.setText(recordTable.getValueAt(SelectedRows, 4).toString());
sc.mobiletxt.setText(recordTable.getValueAt(SelectedRows, 5).toString());
sc.branchtxt.setText(recordTable.getValueAt(SelectedRows, 6).toString());
sc.enterprisetxt.setText(recordTable.getValueAt(SelectedRows, 7).toString());
sc.degreetxt.setText(recordTable.getValueAt(SelectedRows, 8).toString());
sc.countriestxt.setText(recordTable.getValueAt(SelectedRows, 9).toString());
sc.testscoretxt.setText(recordTable.getValueAt(SelectedRows, 10).toString());
sc.engtestscoretxt.setText(recordTable.getValueAt(SelectedRows, 11).toString());
sc.setVisible(true);
    }//GEN-LAST:event_managetblMouseClicked

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataconn,username,password);
            pst=sqlConn.prepareStatement("select * from studentclassdetailscoachingall");

            rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)managetbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {

                String id=String.valueOf(rs.getString("ID"));
                String name=String.valueOf(rs.getString("Name"));
                String age=String.valueOf(rs.getString("Age"));
                String gender=String.valueOf(rs.getString("Gender"));
                String email=String.valueOf(rs.getString("Email"));
                String mobile=String.valueOf(rs.getString("Mobile"));
                String branch=String.valueOf(rs.getString("Branch"));
                String enterprise=String.valueOf(rs.getString("Enterprise"));
                String degree=String.valueOf(rs.getString("Degree"));
                String countries=String.valueOf(rs.getString("Countries"));
               
                String test=String.valueOf(rs.getString("Test"));
                String engtest=String.valueOf(rs.getString("EnglishTest"));

                String tbdata[]={id,name,age,gender,email,mobile,branch,enterprise,degree,countries,test,engtest};

                model.addRow(tbdata);
            }

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconlbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable managetbl;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
