/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VisaEnterprise;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author vatsal
 */
public class VisaDetailsAdminJPanel extends javax.swing.JPanel {
private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/finalproject";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     int q,i;
     String branch;
     String enterprise;
     String name,pass,test;
     byte[] image;
     String englishtest,status;
    /**
     * Creates new form VisaDetailsJPanel
     */
    public VisaDetailsAdminJPanel() {
        initComponents();
    }
public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailsvisaall");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
   
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            
                for(i=1;i<q;i++){
                  
                  columnData.add(rs.getString("ID"));
                  columnData.add(rs.getString("Name"));
                   columnData.add(rs.getString("Age"));
                  columnData.add(rs.getString("Gender"));
                   columnData.add(rs.getString("Email"));
                  columnData.add(rs.getString("Mobile"));
                   columnData.add(rs.getString("Branch"));
                  columnData.add(rs.getString("Enterprise"));
                   columnData.add(rs.getString("Degree"));
                  columnData.add(rs.getString("Countries"));
                   columnData.add(rs.getString("Test"));
                  columnData.add(rs.getString("EnglishTest"));
  
                  columnData.add(rs.getString("VisaStatus"));
                }         
            
             
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        visatbl = new javax.swing.JTable();
        viewbtn = new javax.swing.JButton();

        visatbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Email", "Mobile", "Branch", "Enterprise", "Degree", "Countries", "TestScore", "EngProficiencyScore", "Status"
            }
        ));
        visatbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visatblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visatbl);

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(viewbtn)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewbtn)
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from studentclassdetailsvisaall");
            
             rs=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)visatbl.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                
                
                String id=String.valueOf(rs.getString("ID"));
                String name=String.valueOf(rs.getString("Name"));
                String age=String.valueOf(rs.getString("Age"));
                String gender=String.valueOf(rs.getString("Gender"));
                String email=String.valueOf(rs.getString("Email"));
                String mobile=String.valueOf(rs.getString("Mobile"));
                String branch=String.valueOf(rs.getString("Branch"));
                String enterprise=String.valueOf(rs.getString("Enterprise"));
                String degree=String.valueOf(rs.getString("Degree"));
                String countries=String.valueOf(rs.getString("Countries"));
               
               
                 test=String.valueOf(rs.getString("Test"));
                englishtest=String.valueOf(rs.getString("EnglishTest"));
                  status =String.valueOf(rs.getString("VisaStatus"));
                
                String tbdata[]={id,name,age,gender,email,mobile,branch,branch,enterprise,degree,countries,test,englishtest,status};
                
                model.addRow(tbdata);
            }
           
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_viewbtnActionPerformed

    private void visatblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visatblMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model=(DefaultTableModel)visatbl.getModel();
         int SelectedRows= visatbl.getSelectedRow();
         
         String nstatus=JOptionPane.showInputDialog(null, "Visa Status",status);
         model.setValueAt(nstatus, SelectedRows, 12);
          
               try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("update studentclassdetailsvisaall set ID=?,Name=?,Age=?,Gender=?,Email=?,Mobile=?,Branch=?,Enterprise=?,Degree=?,Countries=?,Test=?,EnglishTest=?,VisaStatus=? where ID=?");
         
       pst.setString(1,model.getValueAt(SelectedRows, 0).toString());
        pst.setString(2,model.getValueAt(SelectedRows, 1).toString());
        pst.setString(3,model.getValueAt(SelectedRows, 2).toString());
        pst.setString(4,model.getValueAt(SelectedRows, 3).toString());
        pst.setString(5,model.getValueAt(SelectedRows, 4).toString());
        pst.setString(6,model.getValueAt(SelectedRows, 5).toString());
        pst.setString(7,model.getValueAt(SelectedRows, 6).toString());
        pst.setString(8,model.getValueAt(SelectedRows, 7).toString());
        pst.setString(9,model.getValueAt(SelectedRows, 8).toString());
        pst.setString(10,model.getValueAt(SelectedRows, 9).toString());
        pst.setString(11,model.getValueAt(SelectedRows, 10).toString());
        pst.setString(12,model.getValueAt(SelectedRows, 11).toString());
        pst.setString(13,model.getValueAt(SelectedRows, 12).toString());
        pst.setString(14,model.getValueAt(SelectedRows, 0).toString());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Visa Status Updated Successfully");
         changeTable(visatbl,12);
         upDateDb();}                    
catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
         
    }
  
    }//GEN-LAST:event_visatblMouseClicked
public void changeTable(JTable visatbl, int column_index) {
        visatbl.getColumnModel().getColumn(column_index).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable visatbl, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(visatbl, value, isSelected, hasFocus, row, column);
               String status =visatbl.getValueAt(row, 12).toString();
                
                if (status =="Approve") {
                    c.setBackground(Color.GREEN);
                } 
                if (status =="Reject") {
                    c.setBackground(Color.RED);
                } 
                return c;
            }
        });
    }


class MyTableCellRenderer extends DefaultTableCellRenderer {

    @Override
    public Color getBackground() {
        return super.getBackground();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewbtn;
    private javax.swing.JTable visatbl;
    // End of variables declaration//GEN-END:variables
}

